services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"  # 웹 기본 포트(80) 사용
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/nginx/certs:ro
    networks:
      infra_net:
        ipv4_address: 172.19.0.13  
    depends_on:
      - minio
  