# Use root/example as user/password credentials
version: "3.9"

x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "2"

services:
  sample:
    image:
    container_name:
    hostname:
    restart: unless-stopped
    ports:
      -
    expose:
      -
    networks:
      - nt-webserver
      -
    logging: *logging
    labels:
    volumes:
    environment:
      - TZ=${DEFAULT_TIMEZONE}

volumes:
