# infra/cicd/argo-cd-values.yaml
server:
  service:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/address-pool: default

  extraArgs:
    - --insecure # dev용, 실제 prod에서는 TLS/Ingress 사용
  config:
    kustomize.buildOptions: "--enable-alpha-plugins"

    # Notifications 사용
    # (실제 서비스/트리거는 ConfigMap에서 정의)
    "notifications.enabled": "true"

controller:
  metrics:
    enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 128Mi

redis:
  enabled: true
# Image Updater는 별도 chart로 설치
