# infra/storage/local-path-values.yaml
storageClass:
  create: true
  name: local-path
  defaultClass: true # 기본 StorageClass로 설정
  reclaimPolicy: Delete

config:
  # HostPath 기준 로컬 디스크 디렉터리
  nodePathMap:
    - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
      paths:
        - /var/local-path-provisioner # Docker Desktop VM 내부 경로

podDisruptionBudget:
  enabled: true # DaemonSet의 가용성 확보
