# Use root/example as user/password credentials
version: "3.9"

x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "2"

services:
  novu-api:
    image: "ghcr.io/novuhq/novu/api:0.24.0"
    container_name: novu-api
    restart: unless-stopped
    env_file:
      - .env.novu
    networks:
      - nt-webserver
    logging: *logging
    environment:
      - TZ=${DEFAULT_TIMEZONE}
      # NODE_ENV: local
      # API_ROOT_URL: ${API_ROOT_URL}
      # DISABLE_USER_REGISTRATION: ${DISABLE_USER_REGISTRATION}
      # PORT: ${API_PORT}
      # FRONT_BASE_URL: ${FRONT_BASE_URL}
      # MONGO_URL: ${MONGO_URL}
      # MONGO_MIN_POOL_SIZE: ${MONGO_MIN_POOL_SIZE}
      # MONGO_MAX_POOL_SIZE: ${MONGO_MAX_POOL_SIZE}
      # REDIS_HOST: ${VALKEY_PREDIXY_HOSTNAME}
      # REDIS_PORT: ${REDIS_PORT}
      # REDIS_PASSWORD: ${REDIS_PASSWORD}
      - REDIS_DB_INDEX=2
      # REDIS_CACHE_SERVICE_HOST: ${REDIS_CACHE_SERVICE_HOST}
      # REDIS_CACHE_SERVICE_PORT: ${REDIS_CACHE_SERVICE_PORT}
      # S3_LOCAL_STACK: ${S3_LOCAL_STACK}
      # S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      # S3_REGION: ${S3_REGION}
      # AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      # AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      # JWT_SECRET: ${JWT_SECRET}
      # STORE_ENCRYPTION_KEY: ${STORE_ENCRYPTION_KEY}
      # SENTRY_DSN: ${SENTRY_DSN}
      # NEW_RELIC_APP_NAME: ${NEW_RELIC_APP_NAME}
      # NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      # API_CONTEXT_PATH: ${API_CONTEXT_PATH}
    ports:
      - "3000:3000"
  novu-worker:
    image: "ghcr.io/novuhq/novu/worker:0.24.0"
    container_name: novu-worker
    restart: unless-stopped
    networks:
      - nt-webserver
    logging: *logging
    env_file:
      - .env.novu
    environment:
      - TZ=${DEFAULT_TIMEZONE}
      # NODE_ENV: ${NODE_ENV}
      # MONGO_URL: ${MONGO_URL}
      # MONGO_MAX_POOL_SIZE: ${MONGO_MAX_POOL_SIZE}
      # REDIS_HOST: ${VALKEY_PREDIXY_HOSTNAME}
      # REDIS_PORT: ${REDIS_PORT}
      # REDIS_PASSWORD: ${REDIS_PASSWORD}
      - REDIS_DB_INDEX=2
      # REDIS_CACHE_SERVICE_HOST: ${REDIS_CACHE_SERVICE_HOST}
      # REDIS_CACHE_SERVICE_PORT: ${REDIS_CACHE_SERVICE_PORT}
      # S3_LOCAL_STACK: ${S3_LOCAL_STACK}
      # S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      # S3_REGION: ${S3_REGION}
      # AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      # AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      # STORE_ENCRYPTION_KEY: ${STORE_ENCRYPTION_KEY}
      # SENTRY_DSN: ${SENTRY_DSN}
      # NEW_RELIC_APP_NAME: ${NEW_RELIC_APP_NAME}
      # NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      # BROADCAST_QUEUE_CHUNK_SIZE: ${BROADCAST_QUEUE_CHUNK_SIZE}
      # MULTICAST_QUEUE_CHUNK_SIZE: ${MULTICAST_QUEUE_CHUNK_SIZE}

  novu-ws:
    image: "ghcr.io/novuhq/novu/ws:0.24.0"
    container_name: novu-ws
    restart: unless-stopped
    env_file:
      - .env.novu
    networks:
      - nt-webserver
    logging: *logging
    environment:
      - TZ=${DEFAULT_TIMEZONE}
    #   PORT: ${WS_PORT}
    #   NODE_ENV: ${NODE_ENV}
    #   MONGO_URL: ${MONGO_URL}
    #   MONGO_MAX_POOL_SIZE: ${MONGO_MAX_POOL_SIZE}
    #   REDIS_HOST: ${VALKEY_PREDIXY_HOSTNAME}
    #   REDIS_PORT: ${REDIS_PORT}
    #   REDIS_PASSWORD: ${REDIS_PASSWORD}
    #   JWT_SECRET: ${JWT_SECRET}
    #   WS_CONTEXT_PATH: ${WS_CONTEXT_PATH}
    #   NEW_RELIC_APP_NAME: ${NEW_RELIC_APP_NAME}
    #   NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
    ports:
      - "3002:3002"

  novu-web:
    image: "ghcr.io/novuhq/novu/web:0.24.0"
    depends_on:
      - novu-api
      - novu-worker
    env_file:
      - .env.novu
    container_name: novu-web
    restart: unless-stopped
    networks:
      - nt-webserver
    logging: *logging
    environment:
      - TZ=${DEFAULT_TIMEZONE}
      # REACT_APP_API_URL: ${API_ROOT_URL}
      # REACT_APP_ENVIRONMENT: ${NODE_ENV}
      # REACT_APP_WIDGET_EMBED_PATH: ${WIDGET_EMBED_PATH}
      - REACT_APP_DOCKER_HOSTED_ENV='true'
      # REACT_APP_WS_URL: ${REACT_APP_WS_URL}
    ports:
      - 4200:4200

  novu-widget:
    image: "ghcr.io/novuhq/novu/widget:0.24.0"
    depends_on:
      - novu-api
      - novu-worker
      - novu-web
    env_file:
      - .env.novu
    container_name: novu-widget
    restart: unless-stopped
    networks:
      - nt-webserver
    logging: *logging
    environment:
      - TZ=${DEFAULT_TIMEZONE}
    #   REACT_APP_API_URL: ${API_ROOT_URL}
    #   REACT_APP_WS_URL: ${REACT_APP_WS_URL}
    #   REACT_APP_ENVIRONMENT: ${NODE_ENV}
    #   WIDGET_CONTEXT_PATH: ${WIDGET_CONTEXT_PATH}
    ports:
      - 4750:4500
  novu-embed:
    env_file:
      - .env.novu
    depends_on:
      - novu-widget
    image: "ghcr.io/novuhq/novu/embed:0.24.0"
    container_name: novu-embed
    restart: unless-stopped
    networks:
      - nt-webserver
    logging: *logging
    environment:
      - TZ=${DEFAULT_TIMEZONE}
    #   WIDGET_URL: ${WIDGET_URL}
    #   NEW_RELIC_APP_NAME: ${NEW_RELIC_APP_NAME}
    #   NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
    ports:
      - 4701:4701
