# Use root/example as user/password credentials
version: "3.9"
name: system-design-system

networks:
  nt-design-system:
    name: nt-design-system
    driver: bridge
  nt-webserver:
    external: true
  nt-databases:
    external: true
  nt-message-broker:
    external: true
  nt-observability:
    external: true

include:
  - Design-System/docker-compose.storybook-react-vite.yml
  - Design-System/docker-compose.storybook-react-webpack.yml
  - Design-System/docker-compose.storybook-webcomp-vite.yml
  - Design-System/docker-compose.storybook-webcomp-webpack.yml
