# Use root/example as user/password credentials
version: "3.9"
name: system-message-broker

networks:
  nt-message-broker:
    name: nt-message-broker
    driver: bridge
  nt-webserver:
    external: true
  nt-databases:
    external: true
  nt-observability:
    external: true

include:
  - Message-Broker/docker-compose.kafka.yml
  - Message-Broker/docker-compose.rabbitmq.yml
