# Use root/example as user/password credentials
version: "3.9"
name: system-incident-mngt
networks:
  nt-incident:
    name: nt-incident
    driver: bridge
  nt-webserver:
    external: true
  nt-databases:
    external: true

include:
  - Incident-Management/docker-compose.dispatch.yml
