# Use root/example as user/password credentials
version: "3.9"
name: system-storage

networks:
  nt-storage:
    name: nt-storage
    driver: bridge
  nt-webserver:
    external: true
  nt-observability:
    external: true

include:
  - Storage/docker-compose.minio.yml
