# Use root/example as user/password credentials
version: "3.9"
name: system-devops

networks:
  nt-devops:
    name: nt-devops
    driver: bridge
  nt-webserver:
    external: true
  nt-qa:
    external: true
  nt-databases:
    external: true
  nt-message-broker:
    external: true
  nt-observability:
    external: true

include:
  - DevOps/docker-compose.jenkins.yml
  - DevOps/docker-compose.harbor.yml
