# Use root/example as user/password credentials
version: "3.9"
name: system-supabase
networks:
  nt-supabase:
    name: nt-supabase
    driver: bridge
  nt-webserver:
    external: true
  nt-databases:
    external: true
  nt-storage:
    external: true
  nt-observability:
    external: true

include:
  - Supabase/docker-compose.supabase.yml
