# Use root/example as user/password credentials
version: "3.9"
name: system-project-mgmt

networks:
  nt-projects:
    name: nt-projects
    driver: bridge
  nt-webserver:
    external: true
  nt-databases:
    external: true
  nt-default:
    external: true

include:
  -
