# Use root/example as user/password credentials
version: "3.9"
name: system-data-collector
networks:
  nt-data-collector:
    name: nt-data-collector
    driver: bridge
  nt-webserver:
    external: true
  nt-observability:
    external: true
  nt-databases:
    external: true
  nt-message-broker:
    external: true
  nt-supabase:
    external: true

include:
  - Data-Collector/docker-compose.vector.yml
