x-default-logging: &logging
  driver: 'json-file'
  options:
    max-size: '5m'
    max-file: '2'

services:
  default-spring-gradle:
    build:
      context: .
      dockerfile: Default-Spring-Gradle/Dockerfile
      target: dev_spring_gradle
    image: spring-gradle:latest
    hostname: default-spring-gradle
    container_name: default-spring-gradle
    restart: unless-stopped
    working_dir: /project
    expose:
      - ${DEFAULT_SPRING_PORT}
    ports:
      - ${DEFAULT_SPRING_GRADLE_HOST_PORT}:${DEFAULT_SPRING_PORT}
    networks:
      - nt-private
      - nt-databases
      - nt-message-broker
      - nt-searchengine
    stdin_open: true #docker run -i
    tty: true #docker run -t
    volumes:
      - default-spring-gradle-volume:/project:rw
      - resource-volume:/resources:rw
    logging: *logging

volumes:
  default-spring-gradle-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${DEFAULT_SOURCECODE_DIR}/default-Spring-Gradle
  resource-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${DEFAULT_RESOURCES_DIR}/Contents
