# Use root/example as user/password credentials
version: "3.9"

x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "2"

services:
  storybook-webcomp-webpack:
    build:
      context: ../../_Builds/storybook/webcomponents-webpack
      dockerfile: Dockerfile
    image: storybook-webcomp-webpack:latest
    container_name: storybook-webcomp-webpack
    hostname: storybook-webcomp-webpack
    restart: unless-stopped
    expose:
      - ${STORYBOOK_PORT}
    # ports:
    #   - ${STORYBOOK_WEBCOMPONENT_WEBPACK_PORT}:${STORYBOOK_PORT}
    volumes:
      - storybook-webcomp-webpack-app-volume:/usr/app
    # labels:
    #   - 'traefik.enable=true'
    #   - traefik.docker.network=nt-local
    #   - traefik.http.services.storybook-webcomp.loadbalancer.server.port=6006
    #   - traefik.http.routers.storybook-webcomp.rule=Host(`storybook-webcomp.${DEFAULT_URL}`)
    #   - traefik.http.routers.storybook-webcomp.entrypoints=web
    #   # For https:
    #   - traefik.http.routers.storybook-webcomp-secure.rule=Host(`storybook-webcomp.${DEFAULT_URL}`)
    #   - traefik.http.routers.storybook-webcomp-secure.entrypoints=websecure
    #   - traefik.http.middlewares.web-redirect-websecure.redirectscheme.scheme=https
    #   - traefik.http.routers.storybook-webcomp.middlewares=web-redirect-websecure
    environment:
      - TZ=${DEFAULT_TIMEZONE}
    networks:
      - nt-design-system
      - nt-databases
      - nt-message-broker
      - nt-observability
      - nt-webserver
    logging: *logging

volumes:
  storybook-webcomp-webpack-app-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${DEFAULT_DESIGN_SYSTEM_DIR}/storybook-webcomp-webpack
