# Use root/example as user/password credentials
version: "3.9"

x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "2"

services:
  ngrinder-controller:
    image: ngrinder/controller:3.5.5
    container_name: ngrinder-controller
    hostname: ngrinder-controller
    restart: unless-stopped
    ports:
      - ${NGRINDER_HOST_PORT}:${NGRINDER_PORT}
      - ${NGRINDER_CONTROLLER_HOST_PORT}:${NGRINDER_CONTROLLER_PORT}
      - 12000-12009:12000-12009
    networks:
      - nt-qa
      - nt-webserver
      - nt-databases
    volumes:
      - ngrinder-controller-volume:/opt/ngrinder-controller
    environment:
      - TZ=${DEFAULT_TIMEZONE}
  ngrinder-agent1:
    image: ngrinder/agent:3.5.5
    container_name: ngrinder-agent1
    hostname: ngrinder-agent1
    restart: unless-stopped
    networks:
      - nt-qa
      - nt-databases
    links:
      - ngrinder-controller
    environment:
      - TZ=${DEFAULT_TIMEZONE}
  ngrinder-agent2:
    image: ngrinder/agent:3.5.5
    container_name: ngrinder-agent2
    hostname: ngrinder-agent2
    restart: unless-stopped
    networks:
      - nt-qa
      - nt-databases
    links:
      - ngrinder-controller
    environment:
      - TZ=${DEFAULT_TIMEZONE}

volumes:
  ngrinder-controller-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${DEFAULT_TESTING_DIR}/ngrinder-controller
