services:
  alloy:
    image: grafana/alloy:v1.11.3
    container_name: alloy
    restart: unless-stopped
    user: "0:0"
    command: ["run", "--server.http.listen-addr=0.0.0.0:12345","/etc/alloy/config.river"]
    volumes:
      - ./alloy-docker-config.river:/etc/alloy/config.river:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro # 도커 로그 접근
      - /var/run/docker.sock:/var/run/docker.sock:ro # 도커 메타데이터 접근    
    ports:
      - "${ALLOY_HOST_PORT}:${ALLOY_PORT}"
      - "${ALLOY_OTLP_GRPC_HOST_PORT}:${ALLOY_OTLP_GRPC_PORT}" # OTLP gRPC Receiver
      - "${ALLOY_OTLP_HTTP_HOST_PORT}:${ALLOY_OTLP_HTTP_PORT}" # OTLP HTTP Receiver
    networks:
      - infra_net # 내부 메트릭 수집용
    extra_hosts:
      - "host.docker.internal:host-gateway"