services:
  es-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.2.1
    container_name: es-1
    environment:
      - node.name=es-1
      - cluster.name=${ES_CLUSTER_NAME}
      - discovery.seed_hosts=es-1,es-2,es-3
      - cluster.initial_master_nodes=es-1,es-2,es-3
      - node.roles=master,data,ingest
      - xpack.security.enabled=true
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.keystore.path=/usr/share/elasticsearch/config/certs/elastic-certificates.p12
      - xpack.security.transport.ssl.truststore.path=/usr/share/elasticsearch/config/certs/elastic-certificates.p12
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}      
      - path.repo=/mnt/backup
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
    volumes:
      - es_data_1:/usr/share/elasticsearch/data
      - es_snapshots:/mnt/backup
    networks:
      - infra_net
    ports:
      - "${ES_HOST_PORT}:${ES_PORT}"

  es-2:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.2.1
    container_name: es-2
    environment:
      - node.name=es-2
      - cluster.name=${ES_CLUSTER_NAME}
      - discovery.seed_hosts=es-1,es-2,es-3
      - cluster.initial_master_nodes=es-1,es-2,es-3
      - node.roles=master,data,ingest
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.http.ssl.enabled=false
      - path.repo=/mnt/backup
    mem_limit: 2g
    volumes:
      - es_data_2:/usr/share/elasticsearch/data
      - es_snapshots:/mnt/backup
    networks:
      - infra_net

  es-3:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.2.1
    container_name: es-3
    environment:
      - node.name=es-3
      - cluster.name=${ES_CLUSTER_NAME}
      - discovery.seed_hosts=es-1,es-2,es-3
      - cluster.initial_master_nodes=es-1,es-2,es-3
      - node.roles=master,data,ingest
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.http.ssl.enabled=false
      - path.repo=/mnt/backup
    mem_limit: 2g
    volumes:
      - es_data_3:/usr/share/elasticsearch/data
      - es_snapshots:/mnt/backup
    networks:
      - infra_net

  kibana:
    image: docker.elastic.co/kibana/kibana:9.2.1
    container_name: kibana
    networks:
      - infra_net
    ports:
      - "${KIBANA_HOST_PORT}:${KIBANA_PORT}"
    environment:
      - ELASTICSEARCH_HOSTS=http://es-1:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
    depends_on:
      es-1: { condition: service_started }
      es-2: { condition: service_started }
      es-3: { condition: service_started }

  es-exporter:
    image: prometheuscommunity/elasticsearch-exporter:v1.8.0
    container_name: es-exporter
    ports:
      - "${ES_EXPORTER_HOST_PORT}:${ES_EXPORTER_PORT}"
    networks:
      - infra_net
    command:
      - "--es.uri=http://elastic:${ELASTIC_PASSWORD}@es-1:9200"
    depends_on: [es-1]

volumes:
  # certs:
  #   driver: local
  #   driver_opts:
  #     o: bind
  #     type: none
  #     device: ${DEFAULT_ELASTICSEARCH_DIR}/elasticsearch/certs
  user-dict-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${DEFAULT_CONFIG_DIR}/elasticsearch/user_dictionary
  es_data_1:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${DEFAULT_ELASTICSEARCH_DATA_DIR}/node1
  es_data_2:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${DEFAULT_ELASTICSEARCH_DATA_DIR}/node2
  es_data_3:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${DEFAULT_ELASTICSEARCH_DATA_DIR}/node3
  es_snapshots:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${DEFAULT_ELASTICSEARCH_DATA_DIR}/snapshots
