# Use root/example as user/password credentials
version: '3.9'

x-default-logging: &logging
  driver: 'json-file'
  options:
    max-size: '5m'
    max-file: '2'

networks:
  nt-local:
    external: true

services:
  mattermost:
    image: mattermost/mattermost-team-edition:latest
    container_name: mattermost
    hostname: mattermost
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    pids_limit: 200
    read_only: false
    expose:
      - 8065
      - 8443
    tmpfs:
      - /tmp
    volumes:
      - mattermost-conf-volume:/mattermost/config:rw
      - mattermost-data-volume:/mattermost/data:rw
      - mattermost-logs-volume:/mattermost/logs:rw
      - mattermost-plugins-volume:/mattermost/plugins:rw
      - mattermost-client-plugins-volume:/mattermost/client/plugins:rw
      - mattermost-bleve-indexes-volume:/mattermost/bleve-indexes:rw
      # When you want to use SSO with GitLab, you have to add the cert pki chain of GitLab inside Alpine
      # to avoid Token request failed: certificate signed by unknown authority
      # (link: https://github.com/mattermost/mattermost-server/issues/13059 and https://github.com/mattermost/docker/issues/34)
      # - ${GITLAB_PKI_CHAIN_PATH}:/etc/ssl/certs/pki_chain.pem:ro
    environment:
      # timezone inside container
      - Asia/Seoul

      # necessary Mattermost options/variables (see env.example)
      - MM_SQLSETTINGS_DRIVERNAME
      - MM_SQLSETTINGS_DATASOURCE

      # necessary for bleve
      - MM_BLEVESETTINGS_INDEXDIR

      # additional settings
      - MM_SERVICESETTINGS_SITEURL
    labels:
      - traefik.enable=true
      - traefik.docker.network=nt-local
      - traefik.http.services.mattermost.loadbalancer.server.port=8065
      - traefik.http.routers.mattermost.rule=Host(`mattermost.${DEFAULT_URL}`)
      - traefik.http.routers.mattermost.entrypoints=web
      # For https:
      - traefik.http.routers.mattermost-secure.rule=Host(`mattermost.${DEFAULT_URL}`)
      - traefik.http.routers.mattermost-secure.entrypoints=websecure
      - traefik.http.middlewares.web-redirect-websecure.redirectscheme.scheme=https
      - traefik.http.routers.mattermost.middlewares=web-redirect-websecure
    networks:
      - nt-local
    logging: *logging

volumes:
  mattermost-conf-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${DEFAULT_COLLABORATION_DIR}/mattermost/conf
  mattermost-data-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${DEFAULT_COLLABORATION_DIR}/mattermost/data
  mattermost-logs-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${DEFAULT_COLLABORATION_DIR}/mattermost/logs
  mattermost-plugins-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${DEFAULT_COLLABORATION_DIR}/mattermost/plugins
  mattermost-bleve-indexes-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${DEFAULT_COLLABORATION_DIR}/mattermost/bleve-indexes
  mattermost-client-plugins-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${DEFAULT_COLLABORATION_DIR}/mattermost/client-plugins
