# Use root/example as user/password credentials
version: "3.9"

x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "2"

services:
  huginn:
    image: ghcr.io/huginn/huginn-single-process
    container_name: huginn
    hostname: huginn
    restart: unless-stopped
    expose:
      - 3000
    networks:
      - nt-automation
      - nt-databases
      - nt-webserver
    logging: *logging
    environment:
      - TZ=${DEFAULT_TIMEZONE}
      - MYSQL_PORT_3306_TCP_ADDR=${MYSQL_MASTER_HOSTNAME}
      - MYSQL_ROOT_PASSWORD=${RDBMS_ROOT_PASSWORD}
      - HUGINN_DATABASE_USERNAME=${DEFAULT_USERNAME}
      - HUGINN_DATABASE_PASSWORD=${MYSQL_PASSWORD}
      - HUGINN_DATABASE_NAME=${HUGINN_MYSQL_DBNAME}
      - APP_SECRET_TOKEN=${HUGINN_APP_SECRET_TOKEN}
    # labels:
    #   - traefik.enable=true
    #   - traefik.docker.network=nt-local
    #   - traefik.http.services.huginn.loadbalancer.server.port=3000
    #   - traefik.http.routers.huginn.rule=Host(`huginn.${DEFAULT_URL}`)
    #   - traefik.http.routers.huginn.entrypoints=web
    #   # For https:
    #   - traefik.http.routers.huginn-secure.rule=Host(`huginn.${DEFAULT_URL}`)
    #   - traefik.http.routers.huginn-secure.entrypoints=websecure
    #   - traefik.http.middlewares.web-redirect-websecure.redirectscheme.scheme=https
    #   - traefik.http.routers.huginn.middlewares=web-redirect-websecure

  threaded:
    image: ghcr.io/huginn/huginn-single-process
    command: /scripts/init bin/threaded.rb
    restart: unless-stopped
    networks:
      - nt-automation
      - nt-databases
      - nt-webserver
    logging: *logging
    environment:
      - MYSQL_PORT_3306_TCP_ADDR=${MYSQL_MASTER_HOSTNAME}
      - MYSQL_ROOT_PASSWORD=${RDBMS_ROOT_PASSWORD}
      - HUGINN_DATABASE_USERNAME=${DEFAULT_USERNAME}
      - HUGINN_DATABASE_PASSWORD=${MYSQL_PASSWORD}
      - HUGINN_DATABASE_NAME=${HUGINN_MYSQL_DBNAME}
      - APP_SECRET_TOKEN=${HUGINN_APP_SECRET_TOKEN}
    depends_on:
      - huginn

