# Use root/example as user/password credentials
version: "3.9"

x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "2"

networks:
  nt-local:
    external: true

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: unless-stopped
    container_name: n8n
    hostname: n8n
    ports:
      - ${N8N_HOST_PORT}:${N8N_PORT}
    expose:
      - ${N8N_PORT}
    # labels:
    #   - traefik.enable=true
    #   - traefik.docker.network=nt-local
    #   - traefik.http.services.n8n.loadbalancer.server.port=5678
    #   - traefik.http.routers.n8n.rule=Host(`n8n.${DEFAULT_URL}`)
    #   - traefik.http.routers.n8n.entrypoints=web
    #   # For https:
    #   - traefik.http.routers.n8n-secure.rule=Host(`n8n.${DEFAULT_URL}`)
    #   - traefik.http.routers.n8n-secure.entrypoints=websecure
    #   - traefik.http.middlewares.web-redirect-websecure.redirectscheme.scheme=https
    #   - traefik.http.routers.n8n.middlewares=web-redirect-websecure
    environment:
      - TZ=${DEFAULT_TIMEZONE}
      # - N8N_HOST=n8n.${DEFAULT_URL}
      - N8N_PORT=${N8N_PORT}
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://n8n.${DEFAULT_URL}/
      - GENERIC_TIMEZONE=${DEFAULT_TIMEZONE}
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=${N8N_POSTGRES_DBNAME}
      - DB_POSTGRESDB_HOST=${POSTGRES_HOSTNAME}
      - DB_POSTGRESDB_PORT=${POSTGRES_PORT}
      - DB_POSTGRESDB_USER=${DEFAULT_USERNAME}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
      - N8N_TEMPLATES_ENABLED=true
      - DB_POSTGRESDB_SCHEMA=${N8N_POSTGRES_SCHEMA}
    volumes:
      - n8n-data-volume:/home/node/.n8n
      - n8n-logs-volume:/var/log/n8n
    networks:
      - nt-automation
      - nt-databases
      - nt-webserver
    logging: *logging

volumes:
  n8n-logs-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${DEFAULT_AUTOMATION_DIR}/n8n/logs
  n8n-data-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${DEFAULT_AUTOMATION_DIR}/n8n/data

