# Use root/example as user/password credentials
version: "3.9"

x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "2"

services:
  automatisch-main:
    build:
      context: ./automatisch
      dockerfile: Dockerfile.compose
    entrypoint: /compose-entrypoint.sh
    container_name: automatisch-main
    hostname: automatisch-main
    expose:
      - 3000
    ports:
      - "3000:3000"
    networks:
      - nt-automation
      - nt-databases
      - nt-webserver
    environment:
      - TZ=${DEFAULT_TIMEZONE}
      - HOST=localhost
      - PROTOCOL=http
      - PORT=3000
      - APP_ENV=production
      - REDIS_HOST=${VALKEY_PREDIXY_HOSTNAME}
      - REDIS_PASSWORD=${VALKEY_PREDIXY_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOSTNAME}
      - POSTGRES_SCHEMA=${AUTOMATISCH_POSTGRES_SCHEMA}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DATABASE=${AUTOMATISCH_POSTGRES_DBNAME}
      - POSTGRES_USERNAME=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ENCRYPTION_KEY
      - WEBHOOK_SECRET_KEY
      - APP_SECRET_KEY
    volumes:
      - automatisch-storage-volume:/automatisch/storage
  automatisch-worker:
    build:
      context: ./automatisch
      dockerfile: Dockerfile.compose
    entrypoint: /compose-entrypoint.sh
    container_name: automatisch-worker
    hostname: automatisch-worker
    depends_on:
      - automatisch-main
    networks:
      - nt-automation
      - nt-databases
      - nt-webserver
    environment:
      - APP_ENV=production
      - REDIS_HOST=${VALKEY_PREDIXY_HOSTNAME}
      - REDIS_PASSWORD=${VALKEY_PREDIXY_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOSTNAME}
      - POSTGRES_SCHEMA=${AUTOMATISCH_POSTGRES_SCHEMA}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DATABASE=${AUTOMATISCH_POSTGRES_DBNAME}
      - POSTGRES_USERNAME=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ENCRYPTION_KEY
      - WEBHOOK_SECRET_KEY
      - APP_SECRET_KEY
      - WORKER=true
    volumes:
      - automatisch-storage-volume:/automatisch/storage

volumes:
  automatisch-storage-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${DEFAULT_AUTOMATION_DIR}/automatisch
