services:
  traefik:
    image: traefik:v3.6.2
    container_name: traefik
    hostname: traefik
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped    
    ports:
      - ${HTTP_HOST_PORT}:${HTTP_PORT}
      - ${HTTPS_HOST_PORT}:${HTTPS_PORT}
      - ${TRAEFIK_DASHBOARD_HOST_PORT}:${TRAEFIK_DASHBOARD_PORT}
      - ${TRAEFIK_METRICS_HOST_PORT}:${TRAEFIK_METRICS_PORT}    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/certs:ro
      - ./dynamic:/dynamic:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
    command:
      # 이제 모든 설정은 파일로 → configFile 한 줄만
      - "--configFile=/etc/traefik/traefik.yml"
    labels:
      # Enable self‑routing
      - "traefik.enable=true"      
      # Dashboard router
      - "traefik.http.routers.dashboard.rule=Host(`dashboard.${DEFAULT_URL}`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls=true"
      # Basic‑auth middleware      
      - "traefik.http.routers.dashboard.middlewares=dashboard-auth@file"
    # healthcheck:
    #   test: ['CMD', 'traefik', 'healthcheck', '--ping']
    #   interval: 10s
    #   timeout: 10s
    #   retries: 30
    networks:
      infra_net:
        ipv4_address: 172.19.0.13
        aliases:
          - keycloak.${DEFAULT_URL}
          - auth.${DEFAULT_URL}
          - whoami.${DEFAULT_URL}
    logging: 
      driver: 'json-file'
      options:
        max-size: '5m'
        max-file: '2'  
  # whoami:
  #   image: traefik/whoami
  #   container_name: whoami
  #   restart: unless-stopped
  #   environment:
  #      # Asia/Seoul
  #   networks:
  #     - infra_net
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.whoami.rule=Host(`whoami.${DEFAULT_URL}`)"
  #     - "traefik.http.routers.whoami.entrypoints=websecure"
  #     - "traefik.http.routers.whoami.tls=true"
  #     - "traefik.http.routers.whoami.middlewares=sso-auth@file"
  #     # - "traefik.http.services.whoami.loadbalancer.server.port=80"