version: '3'
services:
  app:
    build:
      context: ./focalboard/
      dockerfile: docker/Dockerfile
    container_name: focalboard
    volumes:
      - fbdata:/opt/focalboard/data
    ports:
      - 80:8000
    environment:
      - TZ=${DEFAULT_TIMEZONE}
      - VIRTUAL_HOST=focalboard.local
      - VIRTUAL_PORT=8000

volumes:
  fbdata:
